/**
 * Copyright (C) 2010 dennis zhuang (killme2008@gmail.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 **/

package com.googlecode.aviator.runtime.type.string;

import java.util.Map;
import com.googlecode.aviator.Expression;

/**
 * A string segment that generated by an expression execution.
 *
 * @author dennis(killme2008@gmail.com)
 *
 */
public class ExpressionSegment implements StringSegment {
  Expression exp;

  public ExpressionSegment(final Expression exp) {
    super();
    this.exp = exp;
  }

  @Override
  public StringBuilder appendTo(final StringBuilder sb, final Map<String, Object> env) {
    return sb.append(this.exp.execute(env));
  }

  @Override
  public String toString() {
    return "ExpressionSegment [exp=" + this.exp + "]";
  }

}
